//
//  OAuthFlows.swift
//  UsageLimitsKit
//
//  OAuth 2.0 login plumbing shared by every provider integration: the
//  authorisation-code flow with PKCE (RFC 7636) and the Device Authorization
//  Grant (RFC 8628).
//
//  Policy, stated up front: this kit only ever signs users in through a
//  provider's normal, published login flows. Nothing in this file scrapes
//  behind a login page, forges browser headers, or tries to get past a
//  CAPTCHA or bot check. If a provider's edge rejects an ordinary client,
//  the right response is to report that provider as unsupported — never to
//  disguise the request. The security decisions below (constant-time state
//  comparison, S256-only PKCE, a random source that refuses to degrade)
//  exist to protect the legitimate flow; they never attempt to defeat
//  anyone's protections.
//

import Foundation

#if canImport(Security)
import Security
#endif

// MARK: - PKCE (RFC 7636)

/// One half of a PKCE pair (RFC 7636), as generated by `PKCE.generate`.
public struct PKCEChallenge: Sendable, Equatable {

    /// The code verifier: 43–128 characters from the RFC 3986 unreserved set.
    ///
    /// This is a *secret*. It stays client-side until it is posted, together
    /// with the authorisation code, to the token endpoint — that pairing is
    /// what proves the code was issued to this client rather than stolen by
    /// another page on the machine. Never log it, never copy it into an error
    /// message, analytics event or crash report.
    public let verifier: String

    /// The code challenge: `BASE64URL(SHA-256(verifier))` with all padding
    /// omitted (RFC 7636 §4.2). Only this half travels in the authorisation
    /// request; it is safe to have next to the URL because it is a one-way
    /// function of the secret.
    public let challenge: String

    /// Always `S256`. RFC 7636 also defines the un-hashed `plain` method, but
    /// it exists only for servers that cannot hash; this kit refuses to use
    /// it because the challenge is only worth having when it hides the
    /// secret.
    public let method = "S256"

    /// Builds a challenge from an existing verifier. In practice use
    /// `PKCE.generate`, which derives the pair together.
    public init(verifier: String, challenge: String) {
        self.verifier = verifier
        self.challenge = challenge
    }
}

/// Generation of RFC 7636 verifier/challenge pairs.
///
/// This kit is a public OAuth client with no client secret, so PKCE is the
/// mechanism that makes the authorisation-code flow safe for it; every
/// provider sign-in uses it. Nothing here performs network I/O — issuing the
/// request and exchanging the code are the caller's job.
public enum PKCE {

    /// Generates a fresh verifier/challenge pair.
    ///
    /// RFC 7636 §4.1 recommends at least 32 octets of entropy; 32 octets is
    /// also the sweet spot here because base64url-encoding them yields
    /// exactly 43 characters — the minimum length the RFC permits — with no
    /// rounding surprises left to validate against.
    ///
    /// - Parameter randomBytes: source of entropy. Injectable purely so that
    ///   tests can make generation deterministic; production callers use the
    ///   default, the operating system's CSPRNG. It must supply exactly the
    ///   number of bytes requested — a short result is a programming error
    ///   and traps rather than silently weakening the verifier.
    public static func generate(randomBytes: (Int) -> [UInt8] = PKCE.secureRandom) -> PKCEChallenge {
        let entropy = randomBytes(32)
        precondition(entropy.count == 32, "the random source must return exactly the requested number of bytes")

        // The base64url alphabet is a subset of the RFC 3986 unreserved
        // characters, so the encoded verifier is always legal as-is.
        let verifier = Base64URL.encode(entropy)
        precondition(
            (43...128).contains(verifier.count),
            "the verifier must be 43-128 characters long (RFC 7636 §4.1)"
        )

        // RFC 7636 §4.2: challenge = BASE64URL(SHA-256(verifier)), unpadded.
        let challenge = Base64URL.encode(SHA256.hash(Array(verifier.utf8)))
        return PKCEChallenge(verifier: verifier, challenge: challenge)
    }

    /// Returns `count` bytes from the platform's cryptographic random source.
    ///
    /// Darwin uses the Security framework's audited generator; every other
    /// platform this kit builds for (Linux) reads the kernel CSPRNG at
    /// `/dev/urandom`, which does not block and is reseeded from the same
    /// entropy pool as `getrandom(2)`.
    ///
    /// WHY this fails hard instead of degrading: the entire point of a PKCE
    /// verifier — and of a `state` value — is that an attacker cannot guess
    /// it. If the CSPRNG were unavailable and this quietly substituted
    /// `SystemRandomNumberGenerator` or any weaker source, a predictable
    /// verifier would let an attacker intercept the authorisation code,
    /// which is precisely the attack PKCE exists to prevent. An unavailable
    /// CSPRNG is therefore an unrecoverable environment error that stops the
    /// process immediately; it is never a condition we paper over with a
    /// non-cryptographic generator. (The failure messages deliberately carry
    /// only an OS status code, never any key material — there is none yet.)
    public static func secureRandom(_ count: Int) -> [UInt8] {
        precondition(count > 0, "secureRandom requires a positive byte count")

        #if canImport(Security)
        var bytes = [UInt8](repeating: 0, count: count)
        let status: OSStatus = bytes.withUnsafeMutableBytes { rawBuffer in
            guard let destination = rawBuffer.bindMemory(to: UInt8.self).baseAddress else {
                // Unreachable for count > 0, which the precondition above
                // guarantees: a non-empty array always has storage.
                return errSecAllocate
            }
            return SecRandomCopyBytes(kSecRandomDefault, count, destination)
        }
        guard status == errSecSuccess else {
            fatalError("PKCE.secureRandom: SecRandomCopyBytes failed (status \(status)); refusing to continue with a weaker random source")
        }
        return bytes
        #else
        guard let urandom = FileHandle(forReadingAtPath: "/dev/urandom") else {
            fatalError("PKCE.secureRandom: /dev/urandom could not be opened; refusing to continue with a weaker random source")
        }
        defer { try? urandom.close() }

        // Loop because a single read() may legitimately return fewer bytes
        // than requested; only a short total is an error.
        var collected = Data()
        while collected.count < count {
            guard let chunk = try? urandom.read(upToCount: count - collected.count), !chunk.isEmpty else {
                fatalError("PKCE.secureRandom: /dev/urandom returned no data; refusing to continue with a weaker random source")
            }
            collected.append(chunk)
        }
        return [UInt8](collected)
        #endif
    }
}

// MARK: - Authorisation request

/// The authorisation request for the code flow with PKCE: everything needed
/// to build the URL the user is sent to (RFC 6749 §4.1.1 + RFC 7636 §4.5).
///
/// The struct is inert data on purpose. Loading the URL happens in the
/// platform's ordinary browser or system web flow — the user always signs in
/// through the provider's published login pages, never through anything
/// this kit renders or drives itself.
public struct AuthorizationRequest: Sendable {

    /// The provider's authorisation endpoint, exactly as published in its
    /// ordinary OAuth documentation. Expected to be a bare URL: any query
    /// string it already carries is replaced when `url` is built.
    public let authorizationEndpoint: String

    /// The client identifier the provider issued to this app.
    public let clientID: String

    /// Where the provider should redirect back to after sign-in.
    public let redirectURI: String

    /// Space-separated scope string, exactly as the provider documents it.
    public let scope: String

    /// Unguessable, single-use anti-CSRF value. Generate one fresh per
    /// attempt (32 bytes from `PKCE.secureRandom`, hex- or base64url-encoded,
    /// is plenty) and hold on to it until the redirect is validated by
    /// `OAuthFlows.code(from:expectedState:)`.
    public let state: String

    /// The PKCE pair for this attempt. Send `challenge`; keep `verifier`.
    public let pkce: PKCEChallenge

    /// Provider-specific extras (for example `audience` or `prompt`).
    /// Emitted after the standard parameters, in ascending key order; a key
    /// that collides with a standard parameter is ignored so that callers
    /// cannot smuggle in a second `state` or `response_type`.
    public let extraParameters: [String: String]

    public init(
        authorizationEndpoint: String,
        clientID: String,
        redirectURI: String,
        scope: String,
        state: String,
        pkce: PKCEChallenge,
        extraParameters: [String: String] = [:]
    ) {
        self.authorizationEndpoint = authorizationEndpoint
        self.clientID = clientID
        self.redirectURI = redirectURI
        self.scope = scope
        self.state = state
        self.pkce = pkce
        self.extraParameters = extraParameters
    }

    /// The full authorisation URL, or nil when `authorizationEndpoint` is
    /// not parseable as a URL.
    ///
    /// Determinism is deliberate and load-bearing for the tests: the seven
    /// standard parameters are emitted in the fixed order below and the
    /// extras in ascending key order, so structurally equal requests always
    /// produce a byte-identical URL. The query is assembled by hand rather
    /// than through `URLComponents.queryItems` because query-item ordering
    /// and percent-escaping behaviour differ subtly between Foundation
    /// implementations; the escaping itself is likewise hand-rolled (RFC
    /// 3986 unreserved characters pass through, everything else becomes two
    /// uppercase hex digits) so one exact string can be pinned by tests on
    /// every platform. All seven standard parameters are always present; an
    /// empty value is sent as empty (a caller with no scope still sends
    /// `scope=`).
    public var url: URL? {
        guard !authorizationEndpoint.isEmpty,
              var components = URLComponents(string: authorizationEndpoint) else {
            return nil
        }

        // RFC 6749 §4.1.1 plus the PKCE parameters of RFC 7636 §4.5, in a
        // fixed, documented order.
        let standardParameters: [(name: String, value: String)] = [
            ("response_type", "code"),
            ("client_id", clientID),
            ("redirect_uri", redirectURI),
            ("scope", scope),
            ("state", state),
            ("code_challenge", pkce.challenge),
            ("code_challenge_method", pkce.method),
        ]

        let reservedNames = Set(standardParameters.map { $0.name })
        let sortedExtraParameters: [(name: String, value: String)] = extraParameters
            .filter { !$0.key.isEmpty && !reservedNames.contains($0.key) }
            .sorted { $0.key < $1.key }
            .map { (name: $0.key, value: $0.value) }

        let query = (standardParameters + sortedExtraParameters)
            .map { QueryEncoding.encodeComponent($0.name) + "=" + QueryEncoding.encodeComponent($0.value) }
            .joined(separator: "&")

        // Setting the *percent-encoded* query takes the string verbatim, so
        // the ordering and escaping above survive into the final URL.
        components.percentEncodedQuery = query
        return components.url
    }
}

// MARK: - Redirect validation

/// Why a provider's redirect back to us could not be turned into an
/// authorisation code.
public enum OAuthCallbackError: Error, Equatable {

    /// The `state` in the redirect did not match the one we sent, or was
    /// missing entirely. Until state matches, nothing else in the redirect
    /// can be attributed to the request we started, so the whole callback is
    /// discarded — this is the login-flow CSRF defence doing its job.
    case stateMismatch

    /// The state matched but the provider sent no usable `code` parameter.
    case missingCode

    /// The provider completed the redirect with an OAuth error instead of a
    /// code (RFC 6749 §4.1.2.1). This is a normal outcome of the published
    /// login flow — the user declined consent, SSO failed, and so on — not a
    /// reason to retry by other means.
    ///
    /// `description` mirrors the provider's `error_description`. It is
    /// completely untrusted, provider-controlled text: carry it as plain
    /// data at most. Never interpolate it into HTML, Markdown, a templated
    /// alert or anywhere else it could be interpreted as markup or
    /// directives, never auto-link or execute it, and never splice it into a
    /// log line alongside codes, tokens or verifiers. The `code` itself
    /// (e.g. `access_denied`) is an RFC-defined identifier and is safe to
    /// switch on.
    case providerError(code: String, description: String?)
}

// MARK: - Device Authorization Grant (RFC 8628)

/// A provider's response to a device-authorisation request (RFC 8628 §3.2):
/// what to show the user, what to poll with, and for how long.
public struct DeviceAuthorization: Sendable {

    /// The provider's handle on this attempt. Equivalent to a credential
    /// within this grant: only the token endpoint should ever see it.
    public let deviceCode: String

    /// The short, human-typable code the user must enter at
    /// `verificationURI`. Show it prominently with obvious spacing; it is
    /// short-lived and not secret.
    public let userCode: String

    /// The provider's published verification page — the user's sign-in
    /// happens there, in the browser, through the provider's normal login
    /// flow. This kit never drives that page itself.
    public let verificationURI: String

    /// The verification page with the user code pre-filled, when the
    /// provider offers one; open this in preference to `verificationURI`
    /// when present.
    public let verificationURIComplete: String?

    /// The instant after which the provider will refuse the device code.
    /// Derived from `expires_in` and the passed-in clock, so callers do not
    /// each have to reinterpret the provider's relative value.
    public let expiresAt: Date

    /// The minimum number of seconds between token polls. Five when the
    /// provider omits `interval` — the RFC 8628 default; `slowDown` outcomes
    /// add five seconds to whatever interval is in force.
    public let interval: TimeInterval

    public init(
        deviceCode: String,
        userCode: String,
        verificationURI: String,
        verificationURIComplete: String?,
        expiresAt: Date,
        interval: TimeInterval
    ) {
        self.deviceCode = deviceCode
        self.userCode = userCode
        self.verificationURI = verificationURI
        self.verificationURIComplete = verificationURIComplete
        self.expiresAt = expiresAt
        self.interval = interval
    }
}

/// The outcome of one poll of the token endpoint during the Device
/// Authorization Grant (RFC 8628 §3.5).
public enum DevicePollOutcome: Sendable, Equatable {

    /// The user has not finished signing in. Poll again after the current
    /// interval; do not reset any back-off already in force.
    case pending

    /// The provider asked for a slower cadence: wait `newInterval` seconds
    /// before the next poll and keep using `newInterval` for subsequent
    /// polls.
    case slowDown(newInterval: TimeInterval)

    /// The user (or the provider) refused the sign-in. Do not retry
    /// automatically — the decision was the user's to make.
    case denied

    /// The device code expired before sign-in completed. The grant must be
    /// restarted from a fresh device-authorisation request if the user still
    /// wants in.
    case expired

    /// The grant completed. `accessToken` is a bearer credential: never log
    /// it, never include it in an error, never store it unencrypted.
    /// `refreshToken` is nil when the provider issues none. `expiresAt` is
    /// nil when the response carried no usable `expires_in`.
    case success(accessToken: String, refreshToken: String?, expiresAt: Date?)

    /// The response could not be interpreted. The payload is a short,
    /// machine-readable reason — typically the provider's `error` code, or
    /// one of this kit's own identifiers such as `missing_access_token`. It
    /// never contains a token, an authorisation code, a verifier, or
    /// free-form provider prose such as `error_description`.
    case failure(String)
}

// MARK: - Shared flow mechanics

/// Cross-provider mechanics for the two OAuth flows this kit needs: the
/// authorisation-code redirect and the Device Authorization Grant.
///
/// Provider-specific endpoints, client identifiers and scopes live with each
/// provider's integration; everything here is the protocol-safe plumbing
/// those integrations share.
public enum OAuthFlows {

    // MARK: Redirect validation (authorisation-code flow)

    /// Validates the provider's redirect and extracts the authorisation
    /// code.
    ///
    /// The order of the checks is deliberate and security-relevant: `state`
    /// is verified in constant time *before* anything else in the URL is
    /// read, because the rest of the redirect is untrusted until it has been
    /// proven to belong to the request we started. Only then are `error` and
    /// `code` considered — `error` first, so a malformed response carrying
    /// both is treated as a refusal, not as success.
    ///
    /// - Parameters:
    ///   - callback: the URL the provider redirected the browser back to.
    ///   - expectedState: the `state` issued for this login attempt.
    /// - Returns: the authorisation code. It is a short-lived credential
    ///   bound to this client's PKCE verifier: exchange it at the token
    ///   endpoint promptly, and never log it or embed it in an error.
    /// - Throws: `OAuthCallbackError`.
    public static func code(from callback: URL, expectedState: String) throws -> String {
        var parameters: [String: String] = [:]
        if let items = URLComponents(url: callback, resolvingAgainstBaseURL: false)?.queryItems {
            for item in items where !item.name.isEmpty {
                // A repeated parameter name is not something a well-behaved
                // provider emits; if one appears, the last occurrence wins so
                // that parsing stays deterministic. Whichever copy wins, the
                // state check below still has to pass, so duplicates give an
                // attacker nothing.
                parameters[item.name] = item.value ?? ""
            }
        }

        // 1. Anti-CSRF first, in constant time — see `timingSafeEqual`.
        guard let returnedState = parameters["state"],
              timingSafeEqual(expectedState, returnedState) else {
            throw OAuthCallbackError.stateMismatch
        }

        // 2. Only now is the rest of the redirect worth reading. A provider
        //    error is surfaced verbatim, as data — including its optional
        //    description, which must never be rendered as markup (see
        //    `OAuthCallbackError.providerError`).
        if let error = parameters["error"], !error.isEmpty {
            let description = firstValue(
                in: parameters,
                keys: ["error_description", "errorDescription"]
            )
            throw OAuthCallbackError.providerError(code: error, description: description)
        }

        // 3. Success shape: a code to exchange for tokens.
        guard let code = parameters["code"], !code.isEmpty else {
            throw OAuthCallbackError.missingCode
        }
        return code
    }

    // MARK: Device Authorization Grant (RFC 8628)

    /// Parses a device-authorisation response (RFC 8628 §3.2) into its
    /// strongly typed form.
    ///
    /// Both snake_case and camelCase keys are accepted: the providers this
    /// kit reads quota from serve both conventions, and which one a provider
    /// uses is not something a client should have to guess.
    ///
    /// Returns nil when a REQUIRED member (`device_code`, `user_code`,
    /// `verification_uri`, `expires_in`) is missing or unusable. Deliberately
    /// all-or-nothing: a half-parsed value with an invented expiry or a
    /// guessed interval would misbehave quietly later, whereas nil makes the
    /// caller report the provider as unsupported for this flow — the
    /// documented response to a provider that does not behave as published.
    public static func parseDeviceAuthorization(_ json: [String: Any], now: Date) -> DeviceAuthorization? {
        guard
            let deviceCode = nonEmptyString(in: json, keys: ["device_code", "deviceCode"]),
            let userCode = nonEmptyString(in: json, keys: ["user_code", "userCode"]),
            let verificationURI = nonEmptyString(in: json, keys: ["verification_uri", "verificationUri"]),
            let expiresInSeconds = positiveNumber(in: json, keys: ["expires_in", "expiresIn"])
        else {
            return nil
        }

        let verificationURIComplete = nonEmptyString(in: json, keys: [
            "verification_uri_complete",
            "verificationUriComplete",
            "verificationURIComplete",
        ])

        // RFC 8628 §3.2: a missing (or nonsensical) `interval` means poll no
        // faster than every five seconds — the RFC's stated default.
        let interval = positiveNumber(in: json, keys: ["interval"]) ?? 5

        return DeviceAuthorization(
            deviceCode: deviceCode,
            userCode: userCode,
            verificationURI: verificationURI,
            verificationURIComplete: verificationURIComplete,
            expiresAt: now.addingTimeInterval(expiresInSeconds),
            interval: interval
        )
    }

    /// Interprets one poll of the token endpoint during the Device
    /// Authorization Grant (RFC 8628 §3.5).
    ///
    /// The RFC's error codes are mapped to typed outcomes so a caller cannot
    /// mistake "keep waiting" for failure, or failure for "keep waiting":
    ///
    /// - `authorization_pending` → `.pending`: the user is mid-sign-in; poll
    ///   again after the current interval.
    /// - `slow_down` → `.slowDown`: the RFC *requires* waiting an additional
    ///   five seconds over the current interval, and sticking to the
    ///   increased interval for subsequent polls. A client that ignored this
    ///   would be hammering the provider's token endpoint — rude, and
    ///   grounds for blocking.
    /// - `access_denied` → `.denied`: the user (or provider policy) refused.
    /// - `expired_token` → `.expired`: the device code is dead; restart the
    ///   grant from scratch if the user still wants in.
    /// - any other error code → `.failure` carrying that code.
    ///
    /// A response with neither an `error` nor an `access_token` is malformed
    /// and reported as `.failure`; it is never treated as success by
    /// optimism.
    public static func interpretPoll(_ json: [String: Any], now: Date, currentInterval: TimeInterval) -> DevicePollOutcome {
        if let error = nonEmptyString(in: json, keys: ["error"]) {
            switch error {
            case "authorization_pending":
                return .pending
            case "slow_down":
                return .slowDown(newInterval: currentInterval + 5)
            case "access_denied":
                return .denied
            case "expired_token":
                return .expired
            default:
                // An unknown error code is surfaced as data. It is an
                // RFC-style identifier, not secret material, so carrying it
                // is safe; nothing richer — never an `error_description`,
                // never a token — belongs in a `.failure`.
                return .failure(error)
            }
        }

        guard let accessToken = nonEmptyString(in: json, keys: ["access_token", "accessToken"]) else {
            return .failure("missing_access_token")
        }

        let refreshToken = nonEmptyString(in: json, keys: ["refresh_token", "refreshToken"])
        let expiresInSeconds = positiveNumber(in: json, keys: ["expires_in", "expiresIn"])
        return .success(
            accessToken: accessToken,
            refreshToken: refreshToken,
            expiresAt: expiresInSeconds.map { now.addingTimeInterval($0) }
        )
    }
}

// MARK: OAuthFlows: constant-time comparison

extension OAuthFlows {

    /// Constant-time equality for the redirect `state` check.
    ///
    /// WHY constant time: `state` is the CSRF defence of the code flow. A
    /// naive string comparison returns at the first differing byte, so by
    /// measuring how long the comparison took, a remote attacker can learn
    /// how many leading bytes of the expected state they guessed correctly
    /// and then forge the value a byte at a time. Instead, both sides are
    /// hashed first — giving two fixed-length digests — and folded together
    /// with a branch-free XOR accumulator: the loop performs the same work,
    /// in the same order, whatever the values are, and the single boolean
    /// branch happens only after every byte has been mixed in. Hashing still
    /// reveals the *length* of the inputs (blocks processed), but length is
    /// not the protected quantity — the position of differing content is.
    ///
    /// Digests are compared rather than a keyed HMAC because the expected
    /// state is itself a one-use random value from our own CSPRNG: an
    /// attacker cannot pre-select inputs that would make either digest
    /// repeat, and there is no long-term key material whose comparison
    /// pattern could leak.
    static func timingSafeEqual(_ expected: String, _ received: String) -> Bool {
        timingSafeEqual(Array(expected.utf8), Array(received.utf8))
    }

    /// Digest-fold comparison for byte strings; see `timingSafeEqual(_:_:)`
    /// for why this shape was chosen.
    static func timingSafeEqual(_ expected: [UInt8], _ received: [UInt8]) -> Bool {
        let expectedDigest = SHA256.hash(expected)
        let receivedDigest = SHA256.hash(received)

        var difference: UInt8 = 0
        for index in 0..<SHA256.digestLength {
            difference |= expectedDigest[index] ^ receivedDigest[index]
        }
        // One branch, on one accumulated byte, after all input has been
        // folded in — never on the position of a mismatch.
        return difference == 0
    }
}

// MARK: OAuthFlows: tolerant response reading

extension OAuthFlows {

    /// The first present, non-empty string value among alternative spellings
    /// of a JSON member.
    ///
    /// WHY two spellings: the providers this kit talks to return both
    /// snake_case and camelCase keys — sometimes from the same provider on
    /// different endpoints — so every member is looked up under both forms.
    /// Empty strings count as absent: a provider that sends `""` for a
    /// REQUIRED member has effectively not sent it.
    static func nonEmptyString(in json: [String: Any], keys: [String]) -> String? {
        for key in keys {
            if let value = json[key] as? String, !value.isEmpty {
                return value
            }
        }
        return nil
    }

    /// The first present numeric value among alternative spellings of a JSON
    /// member, accepting any numeric JSON shape and numeric strings (which
    /// some providers emit for `expires_in` and friends).
    static func numberValue(in json: [String: Any], keys: [String]) -> Double? {
        for key in keys {
            if let value = json[key] {
                switch value {
                case let double as Double: return double
                case let integer as Int: return Double(integer)
                case let integer as Int64: return Double(integer)
                case let unsigned as UInt64: return Double(unsigned)
                case let string as String: return Double(string)
                default: continue
                }
            }
        }
        return nil
    }

    /// `numberValue(in:keys:)` restricted to strictly positive values — the
    /// only meaningful range for durations and poll intervals.
    static func positiveNumber(in json: [String: Any], keys: [String]) -> Double? {
        guard let value = numberValue(in: json, keys: keys), value > 0 else { return nil }
        return value
    }

    /// The first present, non-empty value among alternative spellings of a
    /// query parameter.
    static func firstValue(in parameters: [String: String], keys: [String]) -> String? {
        for key in keys {
            if let value = parameters[key], !value.isEmpty {
                return value
            }
        }
        return nil
    }
}

// MARK: - SHA-256 (hand-rolled, FIPS 180-4)

/// A dependency-free SHA-256 (FIPS 180-4 §6.2).
///
/// WHY hand-rolled rather than imported: CryptoKit does not exist on this
/// package's Linux target and CommonCrypto is Darwin-only, so neither can be
/// the shared implementation; adding swift-crypto would drag a C library and
/// a package dependency into a deliberately Foundation-only kit. SHA-256 is a
/// short, closed specification that maps directly onto Swift's fixed-width
/// integers, so implementing it directly keeps every supported platform
/// building from one small file with no dependencies. Correctness is not a
/// matter of trust: it is pinned by the standard's published test vectors
/// (the FIPS 180-4 examples and the NIST CAVP short/long-message suites),
/// asserted by this package's unit tests — e.g. SHA-256("abc") must be
/// ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad.
///
/// Scope: this exists for PKCE challenge derivation (RFC 7636 §4.2) and for
/// constant-time comparison in `OAuthFlows`. It is internal on purpose — it
/// is not a general-purpose hashing service and carries no hardening for
/// hashing secret key material.
enum SHA256 {

    /// The length of a SHA-256 digest, in bytes.
    static let digestLength = 32

    /// Round constants: the first 32 bits of the fractional parts of the
    /// cube roots of the first 64 primes (FIPS 180-4 §4.2.2, step 2).
    private static let roundConstants: [UInt32] = [
        0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5,
        0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
        0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3,
        0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
        0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc,
        0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
        0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7,
        0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
        0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13,
        0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
        0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3,
        0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
        0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5,
        0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
        0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208,
        0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
    ]

    /// Initial chaining values: the first 32 bits of the fractional parts of
    /// the square roots of the first 8 primes (FIPS 180-4 §5.3.3).
    private static let initialChainingValues: [UInt32] = [
        0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a,
        0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19,
    ]

    /// Computes the SHA-256 digest of `message`.
    ///
    /// Follows FIPS 180-4 exactly: §5.1.1 padding, the §6.2.2 message
    /// schedule and compression, big-endian output. All additions use the
    /// wrapping `&+` because the specification defines them modulo 2^32; the
    /// `<<`/`>>`/`^` operators on `UInt32` match the specification's word
    /// operations exactly.
    static func hash(_ message: [UInt8]) -> [UInt8] {
        var state = initialChainingValues

        // §5.1.1 padding: append a single 1 bit (as 0x80), then 0 bits until
        // the message is exactly 8 bytes short of a whole number of 64-byte
        // blocks, then the original length in bits as a 64-bit big-endian
        // integer. The length field is 64 bits in the specification whatever
        // we are hashing, hence the UInt64 even for tiny messages.
        var padded = message
        padded.append(0x80)
        while padded.count % 64 != 56 {
            padded.append(0x00)
        }
        let bitLength = UInt64(message.count) * 8
        for shift in stride(from: 56, through: 0, by: -8) {
            padded.append(UInt8(truncatingIfNeeded: bitLength >> UInt64(shift)))
        }

        // One 512-bit block at a time (§6.2.2 step 2).
        var blockStart = 0
        while blockStart < padded.count {
            // Message schedule: the block's 16 big-endian words, extended to
            // 64 words with the sigma0/sigma1 diffusion functions.
            var w = [UInt32](repeating: 0, count: 64)
            for t in 0..<16 {
                let byteIndex = blockStart + t * 4
                w[t] = (UInt32(padded[byteIndex]) << 24)
                    | (UInt32(padded[byteIndex + 1]) << 16)
                    | (UInt32(padded[byteIndex + 2]) << 8)
                    | UInt32(padded[byteIndex + 3])
            }
            for t in 16..<64 {
                let fifteenBack = w[t - 15]
                let twoBack = w[t - 2]
                let sigma0 = rotr(fifteenBack, 7) ^ rotr(fifteenBack, 18) ^ (fifteenBack >> 3)
                let sigma1 = rotr(twoBack, 17) ^ rotr(twoBack, 19) ^ (twoBack >> 10)
                w[t] = w[t - 16] &+ sigma0 &+ w[t - 7] &+ sigma1
            }

            // Compression: eight working variables, 64 rounds of Ch/Maj
            // and big-sigma mixing, then the round result is folded back
            // into the running state with modulo-2^32 addition.
            var a = state[0], b = state[1], c = state[2], d = state[3]
            var e = state[4], f = state[5], g = state[6], h = state[7]
            for t in 0..<64 {
                let bigSigma1 = rotr(e, 6) ^ rotr(e, 11) ^ rotr(e, 25)
                let choice = (e & f) ^ (~e & g)
                let temp1 = h &+ bigSigma1 &+ choice &+ roundConstants[t] &+ w[t]
                let bigSigma0 = rotr(a, 2) ^ rotr(a, 13) ^ rotr(a, 22)
                let majority = (a & b) ^ (a & c) ^ (b & c)
                let temp2 = bigSigma0 &+ majority

                h = g
                g = f
                f = e
                e = d &+ temp1
                d = c
                c = b
                b = a
                a = temp1 &+ temp2
            }
            state[0] &+= a
            state[1] &+= b
            state[2] &+= c
            state[3] &+= d
            state[4] &+= e
            state[5] &+= f
            state[6] &+= g
            state[7] &+= h

            blockStart += 64
        }

        // §6.2.2 step 5: serialise the state words big-endian into 32 bytes.
        var digest = [UInt8]()
        digest.reserveCapacity(digestLength)
        for word in state {
            digest.append(UInt8(truncatingIfNeeded: word >> 24))
            digest.append(UInt8(truncatingIfNeeded: word >> 16))
            digest.append(UInt8(truncatingIfNeeded: word >> 8))
            digest.append(UInt8(truncatingIfNeeded: word))
        }
        return digest
    }

    /// ROTR_n(x) from FIPS 180-4 §3.2: rotate `value` right by `count` bits.
    /// Every call site uses a count in 1...31, so `32 - count` is itself
    /// always in 1...31 and neither shift degenerates into a full-word shift.
    private static func rotr(_ value: UInt32, _ count: UInt32) -> UInt32 {
        (value >> count) | (value << (32 - count))
    }
}

// MARK: - Base64url (hand-rolled, RFC 4648 §5)

/// Unpadded base64url encoding.
///
/// WHY hand-rolled rather than `Data.base64EncodedString()` plus
/// post-processing: the two-step Foundation route produces padded standard
/// base64 first and rewrites it afterwards — more allocation, and one more
/// place where Foundation implementations have historically differed in the
/// small details. A direct three-bytes-to-four-characters encoder is a dozen
/// lines, is identical on every platform, and is pinned by the RFC 4648 test
/// vectors in this package's unit tests.
enum Base64URL {

    /// The RFC 4648 §5 "URL and Filename safe" alphabet: standard base64
    /// with '+' replaced by '-' and '/' by '_'. Every character is also in
    /// the RFC 3986 unreserved set, which is why base64url output can be
    /// dropped straight into a code verifier or a query value without any
    /// escaping.
    private static let alphabet: [Character] = Array(
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"
    )

    /// Encodes `bytes` as base64url with all padding omitted — the exact
    /// form RFC 7636 §4.1 and §4.2 specify for the PKCE verifier and
    /// challenge ("...with all trailing '=' characters omitted").
    static func encode(_ bytes: [UInt8]) -> String {
        var encoded = ""
        // Worst case (a whole number of triplets) is 4 output characters per
        // 3 input bytes; remainders produce one fewer than that.
        encoded.reserveCapacity((bytes.count + 2) / 3 * 4)

        var index = 0
        while index + 3 <= bytes.count {
            let triplet = (UInt32(bytes[index]) << 16)
                | (UInt32(bytes[index + 1]) << 8)
                | UInt32(bytes[index + 2])
            encoded.append(alphabet[Int((triplet >> 18) & 63)])
            encoded.append(alphabet[Int((triplet >> 12) & 63)])
            encoded.append(alphabet[Int((triplet >> 6) & 63)])
            encoded.append(alphabet[Int(triplet & 63)])
            index += 3
        }

        let remainder = bytes.count - index
        if remainder == 1 {
            let octet = UInt32(bytes[index])
            encoded.append(alphabet[Int(octet >> 2)])
            encoded.append(alphabet[Int((octet << 4) & 63)])
            // RFC 4648 would append "==" here; RFC 7636 omits all padding.
        } else if remainder == 2 {
            let pair = (UInt32(bytes[index]) << 8) | UInt32(bytes[index + 1])
            encoded.append(alphabet[Int(pair >> 10)])
            encoded.append(alphabet[Int((pair >> 4) & 63)])
            encoded.append(alphabet[Int((pair << 2) & 63)])
            // RFC 4648 would append "=" here; RFC 7636 omits it.
        }
        return encoded
    }
}

// MARK: - Percent-encoding (hand-rolled, RFC 3986)

/// Percent-encoding for query names and values.
///
/// WHY hand-rolled rather than
/// `addingPercentEncoding(withAllowedCharacters:)`: Foundation's encoder
/// leaves the allowed set to the caller and its treatment of an
/// already-present '%' has differed between Darwin and corelibs. A direct
/// byte-wise encoder that escapes everything outside the RFC 3986
/// unreserved set has exactly one behaviour, emits uppercase hex (which
/// RFC 3986 §2.1 says producers SHOULD use), and gives byte-identical
/// authorisation URLs on every platform — which the determinism of
/// `AuthorizationRequest.url` depends on.
enum QueryEncoding {

    private static let hexadecimalDigits: [Character] = Array("0123456789ABCDEF")

    /// Whether `byte` belongs to the RFC 3986 unreserved set —
    /// ALPHA / DIGIT / "-" / "." / "_" / "~" — and may therefore appear in a
    /// query component unescaped.
    static func isUnreserved(_ byte: UInt8) -> Bool {
        switch byte {
        case 0x41...0x5A, // A-Z
             0x61...0x7A, // a-z
             0x30...0x39, // 0-9
             0x2D,        // "-"
             0x2E,        // "."
             0x5F,        // "_"
             0x7E:        // "~"
            return true
        default:
            return false
        }
    }

    /// Percent-encodes `component` as an RFC 3986 query name or value:
    /// unreserved bytes pass through; every other byte of the UTF-8
    /// serialisation becomes "%" followed by two uppercase hexadecimal
    /// digits. Escaping at the byte level (rather than per Character) keeps
    /// multi-byte characters encoded correctly, one %XX per UTF-8 byte.
    static func encodeComponent(_ component: String) -> String {
        var encoded = ""
        encoded.reserveCapacity(component.utf8.count)
        for byte in component.utf8 {
            if isUnreserved(byte) {
                encoded.append(Character(UnicodeScalar(byte)))
            } else {
                encoded.append("%")
                encoded.append(hexadecimalDigits[Int(byte >> 4)])
                encoded.append(hexadecimalDigits[Int(byte & 0x0F)])
            }
        }
        return encoded
    }
}